---
# Reference: https://access.redhat.com/solutions/1282013

- name: Configure LVM filters
  blockinfile:
    path: /etc/lvm/lvm.conf
    create: yes
    state: '{{"present" if mdss_lvm_filters != [] else "absent"}}'
    insertafter: '^devices {'
    marker: '# {mark} ANSIBLE MANAGED BLOCK: filters'
    block: |2
              filter = {{mdss_lvm_filters | to_json}}
              global_filter = {{mdss_lvm_filters | to_json}}
  register: mdss__r_lvm

- block:
    - name: Rebuild initramfs
      command: dracut --force

    - name: Restart server
      shell: sleep 5 && /sbin/shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for reboot
      wait_for_connection: timeout=300 delay=30

  when: mdss__r_lvm.changed

